name: Analyzer
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  analyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: test5000009/action-golang-analysis@9e8eddbf3e284f6993b50bbb47256dcc9d7cc0e9
        with:
          analyzers: |
            go.sia.tech/jape.Analyzer
          directories: |
            ./api
          flags:
            japecheck.cprefix="/api"
