name: Analyzer
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  analyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: test5000009/action-golang-analysis@0aaceaa6e9a6c5d6aebe6e1bf7fc600a4ead8378
        with:
          analyzers: |
            go.sia.tech/jape.Analyzer
          directories: |
            ./api

